name: release
on:
  push:
    tags: ['v*.*.*']

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Validate Branch and Tag
        run: |
          git fetch origin main

          TAG_COMMIT=$(git rev-list -n 1 "$GITHUB_REF_NAME")

          if ! git merge-base --is-ancestor "$TAG_COMMIT" origin/main; then
            echo "Tag $GITHUB_REF_NAME is not contained in main"
            exit 1
          fi
      - name: Build
        uses: ./.github/actions/build
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          version=$(git describe --always --dirty $GITHUB_REF_NAME | sed "s/^v//")
          echo "$(git tag -l --format="%(contents:body)" "${GITHUB_REF_NAME}")" > RELEASE_NOTES
          gh release create "${version}" --notes-file RELEASE_NOTES
          gh release upload "${version}" ./pkg/iscenv
